# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Zerui Wang
subtitle: A knowledge pool.
description: Attention is all you need.
keywords: AI
author: Zerui Wang
language: en
timezone: America/New_York

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://ZeruiW.github.io
permalink: post/:abbrlink.html
addrlink:
    alg: crc32
    rep: hex
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: git@github.com:ZeruiW/ZeruiW.github.io.git
  # example, https://github.com/hexojs/hexojs.github.io
  branch: main
  message: publish
  name: ZeruiW
  email: wangzerui418@gmail.com
  ignore_hidden: true
  ignore_pattern: 
      CNAME 

hexo_submit_urls_to_search_engine:
  # 提交最新的 n 个链接
  count: 10
  # 提交修改时间在 n 秒内的链接，单位秒。例如：
  # 有两个文件 a.txt 和 b.txt，分别对应 https://yoursite.com/a.txt 和 https://yoursite.com/b.txt
  # 其更新时间距当前分别为 800s 和 1000s（period 字段设为 900）
  # 则 https://yoursite.com/a.txt 会被提交，https://yoursite.com/b.txt 不会
  period: 900
  # 提交链接的条件，可选值：count | period。不同取值的含义如下：
  # count ：应用上述的 count  配置项，现仅支持此方式
  # period：应用上述的 period 配置项
  submit_condition: count
  # 是否向 Google 提交，可选值：1 | 0（0：否；1：是）
  google: 1
  # 是否向 Bing 提交，可选值：1 | 0（0：否；1：是）
  bing: 1
  # 是否向 Baidu 提交，可选值：1 | 0（0：否；1：是）
  baidu: 1
  # 文本文档的地址，要推送的链接会保存在此文本文档里
  txt_path: submit_urls.txt
  # 在百度站长平台中注册的域名
  baidu_host: https://yoursite.com/
  # 百度自动推送 API 的 token（获取方式见插件文档：https://cjh0613.com/20200603HexoSubmitUrlsToSearchEngine.html）
  baidu_token: xxxxx
  # 在必应站长平台中注册的域名
  bing_host: https://yoursite.com/
  # 必应自动推送 API 的 token（获取方式见插件文档：https://cjh0613.com/20200603HexoSubmitUrlsToSearchEngine.html）
  bing_token: xxxxx
  # 在谷歌站长平台中注册的域名
  google_host: https://yoursite.com/
  # 存放 google key 的 json 文件，放于网站根目录
  google_key_file: google_key.json
  replace: 0  # 是否替换链接中的部分字符串，可选值：1 | 0（0：否；1：是）
  find_what: http://cjh0613.github.io/blog
  replace_with: https://cjh0613.com


mathjax:
  tags: none # 或 'ams' 或 'all'
  single_dollars: true # 启用单个美元符号作为内联（行内）数学公式定界符
  cjk_width: 0.9 # 相对 CJK 字符宽度
  normal_width: 0.6 # 相对正常（等宽）宽度
  append_css: true # 将 CSS 添加到每个页面
  every_page: true # 如果为 true，那么无论每篇文章的前题中的 `mathjax` 设置如何，每页都将由 mathjax 呈现


live2d:
  enable: true    # 是否启用看板娘
  scriptFrom: local    # 默认
  pluginRootPath: live2dw/    # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/    # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/    # 模型文件相对与插件根目录路径
  # scriptFrom: jsdelivr    # jsdelivr CDN
  # scriptFrom: unpkg    # unpkg CDN
  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js    # 你的自定义 url
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  model:
    use: live2d-widget-model-hijiki # npm-module 包的名字
    scale: 1
    hHeadPos: 0.5
    vHeadPos: 0.618
  display:
    superSample: 2
    width: 200
    height: 400
    position: right    # 左侧还是右侧
    hOffset: 0
    vOffset: 0    # 距底部距离
  mobile:
    show: false    # 手机端是否可见，建议不可见否则可能影响阅读
    scale: 0.5
  react:
    opacityDefault: 0.7
    opacityOnHover: 0.2

